### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by ndarville** [reddit-india/indianelectionmeter.github.io#19]
Could be done with CloudFlare’s free tier.
- [x] Find provider
- [ ] Enable HSTS
  - [ ] Register site in [HSTS preload record](https://hstspreload.appspot.com/)

**Comment by wasim117** [comment]
also cloudflare will handle large spike in traffic

**Comment by itsprdp** [comment]
+1 for Cloudflare. Lot's of addons and free stuff

**Comment by sandeepzgk** [comment]
+1 cloudflare as it can minimise the attack vector on the website too. and a CDN .. that is amazing stuff right there

**Comment by ndarville** [comment]
Was just taking a look at CDNs, and while [CloudFlare doesn’t even have any data centres in India](https://www.cloudflare.com/network-map/), [GitHub’s CDN has two](https://www.fastly.com/network). Might be worth doing some studying of which is the fastest for Indians.

**Comment by iAmMrinal0** [comment]
@ndarville CloudFlare just introduced three new data centers in [New Delhi, Mumbai, and Chennai.](https://blog.cloudflare.com/cloudflare-launches-in-india-with-data-centers-in-mumbai-chennai-and-new-delhi/)

**Comment by greyhound291** [comment]
@iAmMrinal0 Welcome!
Have you joined the slack channel?

**Comment by iAmMrinal0** [comment]
@greyhound291 Just did.

**Comment by ndarville** [comment]
@iAmMrinal0 Clearly they follow this project. :)

**Comment by okpatil4u** [comment]
Ok people, I tried letsencrypt, and it works without any problem. I am thinking about using it rather than going for paid https certificates or half-encrypted cloudflare https. Have a look at it at https://letsencrypt.org, and let me know what do you think ?

PS : It's in public beta and will take a few months to be fully functional. We will get our content generators working by then.

**Comment by okpatil4u** [comment]
Site is online with on https, with certificate from letsencrypt. Closing this issue.
